version: '3.8'

services:
  openhab:
    image: "openhab/openhab:latest"
    container_name: openhab
    restart: always
    networks:
      - iot_net
    ports:
      - "8080:8080"
    volumes:
      - openhab_conf:/openhab/conf
      - openhab_userdata:/openhab/userdata

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    networks:
      - iot_net
    environment:
      - INFLUXDB_DB=openhab
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    networks:
      - iot_net
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    networks:
      - iot_net
    ports:
      - "1883:1883"

networks:
  iot_net:
    driver: bridge

volumes:
  openhab_conf:
  openhab_userdata:
  influxdb_data:
